### ISSUE TITLE
feature request: add css-tree to performance benchmark

### ISSUE THREAD

**Issue by bartveneman** [csstools/tokenizer#4]
Hi, author of [projectwallace.com](https://www.projectwallace.com/) here. I'm a 'heavy user' of css tokenizers and currently rewriting the core of https://github.com/projectwallace/css-analyzer to [CSSTree](https://github.com/csstree/csstree). 

Would you mind adding a benchmark for CSSTree here too?

**Comment by jonathantneal** [comment]
Hi @bartveneman,

Here you are. I’m a little surprised with the results. I expected `css-tree` to perform better, but `postcss` easily wins the Bootstrap test.

```
  ┌────────────────────────────────────────────────────┬────────┬────────┬────────┐
  │                      (index)                       │   ms   │ ms/50k │ tokens │
  ├────────────────────────────────────────────────────┼────────┼────────┼────────┤
  │ CSSTree 1 x 7.55 ops/sec ±11.49% (24 runs sampled) │ 132.48 │ 13.87  │ 477434 │
  │ PostCSS 8 x 13.78 ops/sec ±2.73% (39 runs sampled) │ 72.56  │  3.88  │ 935267 │
  │ Tokenizer x 17.09 ops/sec ±1.09% (47 runs sampled) │ 58.52  │  3.09  │ 948045 │
  └────────────────────────────────────────────────────┴────────┴────────┴────────┘

Benchmark: Bootstrap
  ┌──────────────────────────────────────────────────┬──────┬────────┬────────┐
  │                     (index)                      │  ms  │ ms/50k │ tokens │
  ├──────────────────────────────────────────────────┼──────┼────────┼────────┤
  │ CSSTree 1 x 118 ops/sec ±2.39% (77 runs sampled) │ 8.5  │  13.1  │ 32425  │
  │ PostCSS 8 x 408 ops/sec ±0.10% (96 runs sampled) │ 2.45 │  2.4   │ 51170  │
  │ Tokenizer x 288 ops/sec ±0.14% (93 runs sampled) │ 3.48 │  2.92  │ 59566  │
  └──────────────────────────────────────────────────┴──────┴────────┴────────┘
```

— [README.md](https://github.com/csstools/tokenizer/tree/c71aa6a20a908b9e85f17d21c9e78d6ba5315458#benchmarks)

I will compare these again after I add a secondary function to parse CSS into component values. I’m using this project as-is to transform CSS, knowing I get accurate tokenization and close-to PostCSS speeds.

**Comment by bartveneman** [comment]
I did *not* expect that either 😱 (luckily, it won't change my opinion of CSSTree)

Thanks for adding this!

**Comment by lahmatiy** [comment]
The benchmark for CSSTree is not fair since includes tokenization, parsing, building AST and its traversal. In fact it does much more than others. Here is a PR to fix it: https://github.com/csstools/tokenizer/pull/5

Results for tokenization only using CSSTree 1.0 & 2.0:

![image](https://user-images.githubusercontent.com/270491/145484062-597dfd94-ca66-47c1-b120-4ec3f88a0db6.png)
