### ISSUE TITLE
Stringify tokens/Detokenize

### ISSUE THREAD

**Issue by strarsis** [csstools/tokenizer#6]
@jonathantneal: This would be even more useful if the tokens can be stringified back to a string. I want to change something on the token-level and then convert it back to a string.
Is it just a matter of reversing the process (symbols back to their values, concatenating them onto a string)?

```js
let tokens = Array.from(tokenizeCSS(cssText)) // an array of CSSTokens
// manipulate tokens ...
const newCssText = detokenizeCss(tokens); // how to get this detokenized back into a string?
````

This tokenizer would be incredibly useful for manipulating CSS property values.
The existing [browser APIs for this](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleValue/parse) are not well supported and currently do not encompass by far all CSS value tokens.

**Comment by romainmenke** [comment]
Hi @strarsis,

I've added a suggested method for serialization to the README : https://github.com/csstools/tokenizer#serialize-tokens

It is so simple that I don't think it is worth it at this time to add it as a build in function.
